[profile.default]
  bytecode_hash = "none"
  optimizer_runs = 20
  timeout = 30000
  block_gas_limit = 300000000
  gas_limit = 3000000000
  gas_price = 1500000000
  cancun = true
  solc_version = "0.8.25"
  evm_version = 'cancun'
  gas_reports = ["Atlas", "AtlasVerification", "Simulator", "Sorter", "ExecutionEnvironment"]
  fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
  ignore = ["./**/*.t.sol"]
